# Generated by Django 4.0.3 on 2022-08-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='isSold',
            new_name='is_sold',
        ),
    ]
